title: "Paola Nunez"
description: "Blog sobre cosas random que me dan curiosidad."
url: ""
baseurl: ""
lang: "es"
timezone: "America/Argentina/Buenos_Aires"
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

author:
  name: "Paola Nunez"
  role: "Developer"

collections:
  posts:
    output: true

plugins: []
